name: Build and deploy ASP.Net Core app to Azure Web App - app-grantpud-poc-monitor

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/main_app-grantpud-poc-monitor.yml'
  workflow_dispatch:

env:
  SOLUTION_PATH: src/PipelineMonitor.sln
  PROJECT_PATH: src/PipelineMonitor.Api/PipelineMonitor.Api.csproj
  DOTNET_VERSION: '8.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ${{ env.DOTNET_ROOT }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_14CC3A25639A4C1BB2E60EAC8D98927C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1567E5040964405288B3C49E31417DC6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_46003B430A9145D6BF7E496F86E9C634 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-grantpud-poc-monitor'
          slot-name: 'Production'
          package: .
